import { Agent } from "./lib/store";

export const agents: Agent[] = [
    {
        id: "max",
        name: "Max.Clan",
        avatar: "https://mesh.distilled.ai/assets/bitmax-ava-B2JnpoUD.png",
        another: "https://media0.giphy.com/media/v1.Y2lkPTc5MGI3NjExdjlvaHZreDdiZHg4c2V1ODdqc3BoYXJ3emx2M3kzcWc1M2VkNWhkdSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/f8ALtpB5AaZbtiBEhf/giphy.webp",
        video: "",
        website: "https://agents.land",
        telegram: "https://t.me/agentsland",
        twitter: "https://twitter.com/agentsland",
        contract: "DYw8jC...CNSKK",
        token: "$BTC",
        members: 12847,
        desc: "A cutting-edge AI agent built on Distilled AI platform, offering advanced automation and intelligent decision-making capabilities for cryptocurrency trading and portfolio management",
        subDesc: "$BTC serves as the foundational cryptocurrency that powers the entire Bitcoin network, enabling secure, decentralized transactions and store of value across the global digital economy"
    },
    {
        id: "leequid",
        name: "LeeQuid.Clan",
        avatar: "https://storage.distilled.ai/distill/avatar/6pF126XC6ayV8jjCH5QfgKjzBt6ihQoaSGiMq7tzUnbs/81095d1d-dfc4-46d4-9dcf-daf2b2d4d0ba.png",
        another: "https://media3.giphy.com/media/v1.Y2lkPTc5MGI3NjExZzJocWhwYW41OTB3MG00dGw3a2pzbXlpOGxpZXkwczJmc2VwZjlvZyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/jTkbYjIbs02XioSbi6/giphy.webp",
        video: "",
        website: "https://trading.agents.land",
        telegram: "https://t.me/tradingbot",
        twitter: "https://twitter.com/tradingbot",
        contract: "HNWmZa...p4XkL",
        token: "$ETH",
        members: 8392,
        desc: "State-of-the-art trading AI system built on Ethereum, leveraging machine learning algorithms to analyze market patterns and execute optimal trading strategies in real-time",
        subDesc: "$ETH is the native currency of Ethereum, powering smart contracts, DeFi applications, and the entire ecosystem of decentralized innovations built on the Ethereum blockchain"
    },
    {
        id: "happy",
        name: "Happy.Clan",
        avatar: "https://i.ibb.co/XtdcDF2/happy.jpg",
        another: "https://media2.giphy.com/media/v1.Y2lkPTc5MGI3NjExdjBrdnFnZHhwZDhtaW51ZW5lYWlrOW8zbm5kenI3YTQ1M3ljbXZ0ayZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/5xtDarIHieSzSJdmn0A/giphy.webp",
        video: "",
        website: "https://nft.agents.land",
        telegram: "https://t.me/nftbot",
        twitter: "https://twitter.com/nftbot",
        contract: "9kWLxt...mN3vY",
        token: "$SOL",
        members: 6743,
        desc: "Revolutionary AI-powered NFT creation platform that enables artists and creators to generate unique, high-quality digital artworks using advanced machine learning models and creative algorithms",
        subDesc: "$SOL powers the Solana blockchain network, providing lightning-fast transactions and minimal fees for NFT minting, trading, and collection management"
    },
    {
        id: "blackrack",
        name: "BlackRack.Clan",
        avatar: "https://storage.distilled.ai/avatar/blackrack_profile_pic_updated_1.jpg",
        video: "",
        website: "https://defi.agents.land",
        telegram: "https://t.me/defibot",
        twitter: "https://twitter.com/defibot",
        contract: "BvTW8q...kP9Rj",
        token: "$MAX",
        members: 5129,
        desc: "Sophisticated DeFi AI assistant that helps users optimize yield farming strategies, manage liquidity positions, and navigate complex decentralized finance protocols with confidence",
        subDesc: "$MAX token is the backbone of the Agents.land ecosystem, providing governance rights, staking rewards, and exclusive access to premium features across the platform"
    },
    {
        id: "karoi",
        name: "Karoi.Clan",
        avatar: "https://storage.distilled.ai/avatar/karoi_1.jpg",
        video: "",
        website: "https://karoi.agents.land",
        telegram: "https://t.me/karoibot",
        twitter: "https://twitter.com/karoibot",
        contract: "5nKpWx...vM2Hs",
        token: "$KAR",
        members: 15238,
        desc: "Innovative gaming AI platform that enhances player experiences through intelligent NPCs, dynamic world generation, and personalized gameplay adaptation using advanced machine learning",
        subDesc: "$KAR token enables seamless integration between traditional gaming and blockchain technology, powering in-game economies and rewarding players for their achievements"
    },
    {
        id: "nexus",
        name: "Nexus.Clan",
        avatar: "https://storage.distilled.ai/distill/avatar/0x864608efc402e4714b07bc52a49120ff74387a0b/11501780-562c-4f84-af17-6563081d0002.png",
        video: "",
        website: "https://nexus.agents.land",
        telegram: "https://t.me/nexusbot",
        twitter: "https://twitter.com/nexusbot",
        contract: "Jw4Ynq...tL8Px",
        token: "$NEX",
        members: 9876,
        desc: "Advanced cross-chain protocol powered by AI that enables seamless asset transfers and communication between different blockchain networks, optimizing interoperability and efficiency",
        subDesc: "$NEX token facilitates cross-chain transactions and governance across multiple blockchain ecosystems, creating a unified and interconnected network of networks"
    },
    {
        id: "quantum",
        name: "Quantum.Clan",
        avatar: "https://storage.distilled.ai/distill/avatar/0x4675b746489ab4202c45e7cda29c32576a017725/3e2f36e3-5012-4466-ac66-7e2bd07437c3.png",
        video: "",
        website: "https://quantum.agents.land",
        telegram: "https://t.me/quantumbot",
        twitter: "https://twitter.com/quantumbot",
        contract: "Qs9Mkp...hN4Wz",
        token: "$QTM",
        members: 18452,
        desc: "Pioneering research initiative combining quantum computing principles with AI to solve complex blockchain problems and develop next-generation cryptographic solutions",
        subDesc: "$QTM token supports quantum-resistant blockchain development and rewards contributors to quantum computing research in the blockchain space"
    },
    {
        id: "wotoria",
        name: "Wotoria.Clan",
        avatar: "https://storage.distilled.ai/avatar/wotoria.png",
        video: "",
        website: "https://wotoria.agents.land",
        telegram: "https://t.me/wotoriabot",
        twitter: "https://twitter.com/wotoriabot",
        contract: "Xm2Vkr...bT5Ny",
        token: "$WOT",
        members: 7234,
        desc: "Comprehensive social media analytics platform powered by AI that provides deep insights into community engagement, sentiment analysis, and trend prediction for Web3 projects",
        subDesc: "$WOT token enables advanced social analytics features and rewards users for contributing valuable data and insights to the platform's ecosystem"
    },
    {
        id: "zenith",
        name: "Zenith.Clan",
        avatar: "https://storage.distilled.ai/distill/avatar/0xd766f93fd5a5d407c42dbadc4376c6d1678b3085/ab1c28e7-d91c-49af-ab9a-bed8e607c488.png",
        video: "",
        website: "https://zenith.agents.land",
        telegram: "https://t.me/zenithbot",
        twitter: "https://twitter.com/zenithbot",
        contract: "Rp7Hnt...qK6Mw",
        token: "$ZEN",
        members: 11567,
        desc: "AI-powered wellness platform that provides personalized meditation guidance, stress management techniques, and mental health support through advanced natural language processing",
        subDesc: "$ZEN token incentivizes mindfulness practices and wellness activities while building a community-driven ecosystem for mental health and personal development"
    }
];
